### ISSUE TITLE
[BUG] Export failed when a new trait is added to the field

### ISSUE THREAD

**Issue by abatac** [PhenoApps/Field-Book#125] opened 2020-04-06 05:43 UTC
**Describe the bug**
BrAPI export will fail if a new trait is imported into an existing field.

**To Reproduce**
1. Import a field with trait(s) (e.g. Aflatox_M_ppb) from BrAPI
2. In the Collect section, edit the value of Aflatox_M_ppb
3. Click Export > BrAPI > Export
4. Export should be successful
5. Go back to Traits section and import a new trait from BrAPI (e.g. NOTES)
6. In the Collect section, edit the value of NOTES
7.  Click Export > BrAPI > Export
8. BrAPI Export Failed message is displayed.

Note: The PUT /studies/{studyDbId}/observationunits will fail if the observationVariableDbId being uploaded is not yet associated in a field/study. I think there must be a way to sync the traits added in the Field Book app and the study in the BrAPI server.

@BrapiCoordinatorSelby @mcrimi @nahuel-soldevilla

**Expected behavior**
Export should be successful.

**Device Info (please complete the following information):**
 - Model: Anroid Emulator
 - OS: Android 10
 - Field Book Version 4.2

**Additional context**

**Comment by chaneylc** [comment] 2021-11-03 17:50
Hello @abatac could you possibly test this to see if it has been fixed? I tried reproducing this on master branch with the test-server.brapi.org but was not running into your issue.

**Comment by trife** [comment] 2021-11-18 17:18
This can be reopened if the behavior is still persisting but closing for now due to an inability to replicate the bug.

**Closed by trife** 2021-11-18 17:18 UTC
Labels: bug
