### ISSUE TITLE
[REQUEST] Group and Archive Fields

### ISSUE THREAD

**Issue by lagvier** [PhenoApps/Field-Book#289] opened 2021-07-22 17:09 UTC
**Subset number of visible fields on the application as requested by user**

- Add an optional ability to archive fields (useful for completed data collection and export) and remove it from visible fields 
- Add an optional ability to use a field column to indicate visible fields (useful where there many imported fields), the enumerator can show subset of the fields for selection to undertake data collection instead of browsing all the fields.

**Comment by trife** [comment] 2021-07-22 17:10
Duplicate of #163

**Closed by trife** 2021-07-22 17:10 UTC
Labels: enhancement, feature request
