### ISSUE TITLE
[BUG]:  $1 in date trait entry causing crashes

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#677] opened 2023-07-18 22:39 UTC
### Description

I noticed that for one plot in fieldbook the app crashes when moving to  a specific trait. I checked the .db file and I noticed for that trait the plot has "$1" entry. I assume that is why the app is crashing. This is a date trait. No idea how $1 got there. Should I just delete this entry in the database? See attached database file (added a .txt so github would let me upload it). If you look at the 23EF-rep1-22F01005-3-1_1_plant_1 observation_unit_id for the second female flowering date trait in the observations table you will see it.

[backup.db.txt](https://github.com/PhenoApps/Field-Book/files/12089450/backup.db.txt)

### Field Book version

5.4.0

**Comment by trife** [comment] 2023-07-20 23:14
Deleting the row should be fine to resolve the issue. `$1` is used internally with some of the query building so it's likely the issue is related to that. Maybe to the pipes again? I don't know why it would only happen for a single observation though. @chaneylc any thoughts?

**Comment by chaneylc** [comment] 2023-08-10 16:56
My only guess would be that this value was manually inserted into the DB. I'll keep digging and create a PR today that will replace unwanted values like this with "NA" or an empty string.

> Deleting the row should be fine to resolve the issue. `$1` is used internally with some of the query building so it's likely the issue is related to that. Maybe to the pipes again? I don't know why it would only happen for a single observation though. @chaneylc any thoughts?
Slack me more details on what you're thinking, you might be thinking of the string formatting like "`$it`" which wouldn't be the case here.

**Comment by trife** [comment] 2023-08-15 21:06
Closing this and wrapping it into a larger issue #681 related to validating existing data _in addition to_ new data.

**Closed by trife** 2023-08-15 21:06 UTC
Labels: bug
