### ISSUE TITLE
Fix  broken link for cassavabase in the community server section [REQUEST]

### ISSUE THREAD

**Issue by MFlores2021** [PhenoApps/Field-Book#398] opened 2022-03-21 19:25 UTC
In the community servers section Cassavabase brapi link is working with “preferences_brapi_oidc_flow_old_custom”. It should be changed to “preferences_brapi_oidc_flow_oauth_implicit” since Cassavabase is working with oAuth2.

@ClayBirkett: I think also T3 servers should be changed.

**Comment by ClayBirkett** [comment] 2022-03-21 19:46
Yes, the links for T3 should also be updated

**Comment by chaneylc** [comment] 2022-06-23 18:30
This is fixed in develop.

**Comment by ClayBirkett** [comment] 2022-08-30 20:22
The T3 instances work when the settings are correct. I created an instructions to work around the authentication bugs.
https://wheat.triticeaetoolbox.org/static_content/files/FieldBookAppT3.pdf
BrAPI settings: page size 50, BrAPI Base URL
BrAPI Advanced Auth Settings: OIDC Flow, OIDC Discover URL
The app frequently crashes when authenticating but eventually works.

**Comment by chaneylc** [comment] 2022-08-30 20:32
@ClayBirkett I tried following your instructions and I still get:

org.brapi.client.v2.model.exceptions.ApiException: Internal Server Error

Documentation for this error says:
"ApiException – If the response has a unsuccessful status code or fail to deserialize the response body"

This might be a problem with the data served from T3 or a brapi v2 client bug.

**Comment by BrapiCoordinatorSelby** [comment] 2022-08-30 20:36
@chaneylc I just confirmed that with the correct settings CassavaBase also works just fine and I downloaded a study, collected data successfully.
Where are you getting stuck? CassavaBase in particular is very slow, you need to filter by a program and trial before any study results will show up
With that error you just saw, I wonder if there is an API in breedbase that is refusing to respond unless it has some filter to limit the size of the results. That might cause what you are seeing?

**Comment by chaneylc** [comment] 2022-08-30 20:39
@BrapiCoordinatorSelby Yes it looks like cassavabase does work if you filter by program, I'm not seeing the same for wheat.

**Comment by BrapiCoordinatorSelby** [comment] 2022-08-30 20:56
I think I see the issue (or just an issue)
T3 Wheat BrAPI seems to be working as expected. Example: https://wheat.triticeaetoolbox.org/brapi/v2/studies
T3 Wheat SANDBOX BrAPI is throwing server errors. Example: https://wheat-sandbox.triticeaetoolbox.org/brapi/v2/studies

@chaneylc the Sandbox instance is the default in FB, I just downloaded studies correctly from the normal T3 Wheat instance

@ClayBirkett There might be something wrong with BrAPI on your sandbox servers, perhaps they are out of date? or bad data?

**Comment by chaneylc** [comment] 2022-08-30 20:59
Yeah, sorry I should have made that more apparent. All the T3 FB servers are sandbox, should they be the toolbox version?

**Comment by BrapiCoordinatorSelby** [comment] 2022-08-30 21:02
Also, @ClayBirkett from your instructions PDF

> Note: When you see "Your connection is not private", you should select the "Advanced" button then select "Proceed to fieldbook.phenoapps.org (unsafe). The first time you do this step the Field Book App will crash but on the second try it should succeed. 

That shouldn't happen hahahaha. if you haven't already opened a bug report for this, please do so, and we can figure out what the heck is going on together. No one wants the app to crash as a normal part of the login process

**Comment by MFlores2021** [comment] 2022-08-30 21:10
It doesn't crash that much for me. But somehow after the  login I get redirected to Play Store. I choose again Fieldbook and then works fine.
Yeah Cassavabase has many studies and filtering by program helps. Search studies will be a nice feature to have

**Comment by ClayBirkett** [comment] 2022-08-31 14:20
The problem on wheat-sandbox is fixed now. There was a database problem when the machines were synced.

I will run through my test again and report an issue whenever the app crashes.
________________________________

**Comment by trife** [comment] 2022-09-01 18:16
Closing this for now as I think it's fixed in develop. If it occurs after 5.3 has been released feel free to reopen.

**Closed by trife** 2022-09-01 18:16 UTC
Labels: enhancement, feature request
