### ISSUE TITLE
[BUG] Multiple observations per variable

### ISSUE THREAD

**Issue by nahuel-soldevilla** [PhenoApps/Field-Book#257] opened 2021-05-19 19:50 UTC
**Describe the bug**
My apologies, I still didn't have time to verify if this is a problem with BMS data, but I wanted to give early feedback.
This was discovered by @barbacenasmc while testing BMS v18 against Field-book pre-release v5.0, to check the new pagination features.
It was tested using the Original Fieldbook custom Auth method. I'll report back with more info as soon as I can..

cc @BrapiCoordinatorSelby @mcrimi @clarysabel

**To Reproduce**

https://user-images.githubusercontent.com/19394293/118874818-b3d1c480-b8c1-11eb-8a02-f01e46b96d97.mp4

**Expected behavior**
Being able to export data successfully.

**Device Info (please complete the following information):**
 - Model:
 - OS:
 - Field Book Version v5.0

**Additional context**

**Comment by barbacenasmc** [comment] 2021-05-20 00:08
Hi @nahuel-soldevilla , thanks for reporting this. Here are my testing environment details:
**Mobile Device:**
Model: Redmi 6A
OS: Android 8.1.0

**Comment by trife** [comment] 2021-06-09 22:46
@chaneylc can you look into this?

**Comment by trife** [comment] 2021-06-10 18:38
@nahuel-soldevilla we're having a difficult time reproducing this. Are you seeing this on other servers in addition to the bms instance you have? Does this happen with other traits or only a specific format?

**Comment by barbacenasmc** [comment] 2021-06-14 01:34
Hi @trife , yes we experience this in other servers and in any type of traits

**Comment by zrm22** [comment] 2021-06-29 17:18
I think we are running into this as well and might have an idea of what is going on.  I am noticing that when we load in the field using Brapi v1, the number of plots are doubled in the values array in the BrapiStudyDetails object which is used in BrAPIServiceV1.saveStudyDetails().  This is hard to catch unless you have a logging statement in BrapiServiceV1.saveStudyDetails() because the observations are shared between the two copies of the plot, so even if you cycle through the entire field, it all looks ok from the Collect screen.

I noticed this because I tried to sort the plots by plotId and I am now needing to click the next arrow twice to move to the next plot.

Just for reference I have also merged the current develop branch on my Forked branch(on June 28th) and am still seeing the issue.

**Closed** 2021-07-23 15:28 UTC
Labels: bug
