### ISSUE TITLE
[BUG] Problems with barcode scanning and data collection

### ISSUE THREAD

**Issue by Minaella** [PhenoApps/Field-Book#487] opened 2022-08-10 15:12 UTC
**Describe the bug**
I transferred data (Field Book apps, files) from Galaxy Tab A7 Lite to another via Smart Switch (I've done it before with other tablets and everything works). When I tried to use the new A7 it crashes every time I try to scan a barcode it shuts down, after that I can't collect any more data, every time I go to collect , it closes instantly.

**To Reproduce**
1. Go to 'Collect'
2. Field book closes

**Expected behavior**
Be able to scan the barcode and go directly to the desired plot and collect  data

**Screenshots**

**Device Info (please complete the following information):**
 - Model: Galaxy Tab A7 Lite
 - OS:
 - Field Book Version 5.2.5

**Additional context**

**Comment by trife** [comment] 2022-08-19 20:52
Hi @Minaella
I think this issue will be fixed in 5.3. Until then, if you export the database (Settings > Database) from your old tablet and import it into the new tablet, are you able to use Field Book?

**Comment by Minaella** [comment] 2022-08-24 12:54
Dear Trevor,

Actually, I have not tested, I don’t have access to the old tablet (stuck at home due to covid). When the V. 5.3 will be released ?

Meanwhile can you help me with another issue, I am not able to import a file, I had this error message:
“Selected column contains characters which cannot be used in the unique identifier”
Can you help me with this please, I am not able to find the guilty character, I did many tests …

Thank you

Amina

De : Trevor Rife ***@***.***>
Envoyé : 19 août 2022 16:52
À : PhenoApps/Field-Book ***@***.***>
Cc : Amina Abed ***@***.***>; Mention ***@***.***>
Objet : Re: [PhenoApps/Field-Book] [BUG] Problems with barcode scanning and data collection (Issue #487)


Hi @Minaella<https://github.com/Minaella>
I think this issue will be fixed in 5.3. Until then, if you export the database (Settings > Database) from your old tablet and import it into the new tablet, are you able to use Field Book?

**Comment by trife** [comment] 2022-08-29 17:31
If you upload or email me the file I can check it out to see what the issue is. We don't have a set deadline on v5.3 but will hopefully have a beta out soon.

**Comment by trife** [comment] 2022-09-01 18:19
Closing this for now. If this issue reoccurs in 5.3 it can be reopened.

**Closed by trife** 2022-09-01 18:19 UTC
Labels: bug
