### ISSUE TITLE
[BUG]:  Importing more traits deletes existing traits?

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#679] opened 2023-07-19 11:23 UTC
### Description

Is there a way to add new traits to the app without deleting all trait data? When I click import traits, it asks me if want to export the current list, I don't. Then it asks if I want to delete traits, I hit cancel. Then it imports my new traits and deletes all the old ones. Not what I expected.

### Field Book version
5.4.0

**Comment by ch728** [comment] 2023-07-19 11:32
At first I thought it was deleting the trait data, but the data is all still there. It is just deleting removing the traits. The behavior I expected was appending the new traits.

**Comment by trife** [comment] 2023-07-20 23:06
Duplicate of #653 but increasing priority.

This is a vestigial workflow from a very long time ago that was built due to some limitation but we should be able to resolve right now.

**Closed by trife** 2023-07-20 23:06 UTC
Labels: bug
