### ISSUE TITLE
[BUG]: Barcode should be configurable for observationunit_name, not only DbId, when BrAPI is used

### ISSUE THREAD

**Issue by lukasmueller** [PhenoApps/Field-Book#1062] opened 2024-10-17 15:25 UTC
### Description

Currently when importing with BrAPI, fieldbook will only match barcode with DbIds, not the name. With Breedbase, people have traditionally used the observation unit name for the barcode

### Expected behavior

allow barcode to contain the name and search it in the fieldbook

**Comment by trife** [comment] 2024-10-17 15:26
Duplicate of #792

**Closed by trife** 2024-10-17 15:26 UTC
Labels: bug
