### ISSUE TITLE
[BUG]: Problem using the data collect page

### ISSUE THREAD

**Issue by lagvier** [PhenoApps/Field-Book#740] opened 2023-09-22 06:02 UTC
### Description

We have experience a problem while using the application to collect data. After collecting data several times, on a few occasions we are unable to use the data collection interface because all field information turns to NULL in the data collection page as shown in the screenshot attached. 

![image](https://github.com/PhenoApps/Field-Book/assets/2693136/29f36cdf-0b7a-4195-b8a5-654b7bb1b96c)

### Field Book version

5.3.0

**Comment by trife** [comment] 2023-09-22 10:56
This was fixed in a more recent version. Please update via Google Play or from the GitHub releases page. That being said, this issue was caused by a database field being corrupted. I can help recover your data if needed, but installing the update will require you to reimport the field.

**Closed by trife** 2023-09-22 10:56 UTC
Labels: bug
