### ISSUE TITLE
[BUG]:  Camera trait fails depending on trait name 

### ISSUE THREAD

**Issue by ch728** [PhenoApps/Field-Book#771] opened 2023-10-16 17:49 UTC
### Description

Latest version of app. Default  trait export from our breedbase is the trait name  with "|UNH:XXXXX' ontology number . We found that photo traits don't work with the "|UNH:XXXX" part in the name. The camera opens and takes a photo, but the photo doesn't save.  When the "|UNH:XXXX" part is removed the photo saves. Only seems to be an issue for photo traits. See attached working and not working trait files.
[notworking_photo_booth.txt](https://github.com/PhenoApps/Field-Book/files/12920002/notworking_photo_booth.txt)
[working_photo_booth.txt](https://github.com/PhenoApps/Field-Book/files/12920004/working_photo_booth.txt)

**Comment by trife** [comment] 2023-10-17 10:10
Related/duplicate of #641 

I'll test Chaney's fix when I'm back in the office on Wednesday

**Closed** 2023-11-30 18:23 UTC
Labels: bug
